modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId= "cataclysm" #mandatory
version="2.03" #mandatory
# A display name for the mod
displayName="Cataclysm Mod" #mandatory
credits="0dyss2y,HedwigOwls,danimodder,Gibb50" #optional
authors="L_Ender" #optional
description='''
Hello
Also Listen Cataclysmic Tunes
https://www.curseforge.com/minecraft/texture-packs/cataclysmic-tunes
Artist=dogulkkun,mango03034,Gytator,LegendNoob
Patron
[Adam,
Angry Mutant Enderman,
darkMind204,
DENOBODY2,
Hippo0824,
printa,
walker,
참치,
3T,
danimodder,
EternalOne,
Karat Feng,
lucy,
nameed,
PeopleMcNugget,
qwerqweqq,
Svmf2023,
Th3P3dr3nder99]
'''

[[dependencies.cataclysm]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="NONE"
side="BOTH"
